config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/login'
  get 'sessions/welcome'
  get 'drinks/search', to: 'drinks#search' 
  get 'drinks/search', to: 'drinks#handle_search' 
  get 'ingredients/search', to: 'ingredients#search'
  post 'ingredients/search', to: 'ingredients#handle_search'

  resources :drink_ingredients
  resources :ingredients
  resources :drinks
  resources :shelves
  resources :users
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeansBar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %> 
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Gelasio|Source+Sans+Pro&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="#">
    <img src="https://kitchenswagger.com/wp-content/uploads/2015/11/strawberry-cucumber-cocktail2.jpg" alt="Logo" style="width:40px;">
      </a>
  <ul class="navbar-nav">

    <li class="nav-item">
      <a class="nav-link"  href="#"><%= link_to "Users", users_path%></a>
    </li>

    <li class="nav-item">
      <a class="nav-link"  href="#"><%= link_to "Shelves", shelves_path%></a>
    </li>

    <li class="nav-item">
      <a class="nav-link"  href="#"><%= link_to "Drinks", drinks_path%></a>
    </li>

    <li class="nav-item">
      <a class="nav-link"  href="#"><%= link_to "Ingredients", ingredients_path%></a>
    </li>
    
  </ul>
</nav>


    <%= yield %>
  </body>
</html>